stages:
  load_data:
    cmd: uv run python -m src.euroleague_analysis.euroleague_data_collector
    deps:
      - src/euroleague_analysis/euroleague_data_collector.py
    outs:
      - euroleague_data/raw/player_stats_2023.parquet
      - euroleague_data/raw/playbyplay_data_2023.parquet
      - euroleague_data/raw/shot_data_2023.parquet
      - euroleague_data/raw/quarter_data_2023.parquet
      - euroleague_data/raw/end_quarter_data_2023.parquet

  feature_engineering:
    cmd: uv run python -m src.euroleague_analysis.feature_engineering
    deps:
      - src/euroleague_analysis/feature_engineering
      - src/euroleague_analysis/sql_queries
      - euroleague_data/raw/player_stats_2023.parquet
      - euroleague_data/raw/playbyplay_data_2023.parquet
      - euroleague_data/raw/shot_data_2023.parquet
    outs:
      - euroleague_data/features.parquet
      - euroleague_data/features.duckdb
    metrics:
      - feature_outputs.json:
          cache: false