extract:
  seasons: [2023, 2024]
  data_dir: "euroleague_data"
  competition_code: "E"

feature_engineering:
  data_dir: "euroleague_data"  # Changed to match extract section
  output_dir: "euroleague_data"  # Changed from "features" to match DVC expectation
  seasons: ["2023", "2024"]  # Updated to match actual season format
  transformers:  # optional, uses all if not specified
    - combined_stats
    - shot_patterns
    - playbyplay
    - position_matchups

train:
  data_dir: "euroleague_data"
  model_dir: "models"
  max_iter: 100
  learning_rate: 0.1
  max_depth: 5
  min_samples_leaf: 20
  l2_regularization: 1.0
  max_leaf_nodes: null
  validation_fraction: 0.1
  early_stopping: true
  n_iter_no_change: 10
  n_splits: 5

analyze:
  data_dir: "euroleague_data"
  model_dir: "models"
  analysis_dir: "analysis"

train_pgm:
  data_dir: "euroleague_data"
  model_dir: "models_pgm"
  n_samples: 2000
  n_tune: 2000
  n_chains: 2

analyze_pgm:
  data_dir: "euroleague_data"
  model_dir: "models_pgm"
  analysis_dir: "analysis_pgm"